webtalk_init -webtalk_dir /home/k_rakeesh/Documents/CACD_labs/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Lab03_FA_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 25 14:00:00 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b97f8887b20f518ab9d45c84751deb91" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "66a0df696c6a4a8bbd31ad7df572baa1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Pop" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 22.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-1235U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "713.604 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114092_KB" -context "xsim\\usage"
webtalk_transmit -clientid 866649718 -regid "" -xml /home/k_rakeesh/Documents/CACD_labs/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Lab03_FA_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/k_rakeesh/Documents/CACD_labs/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Lab03_FA_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/k_rakeesh/Documents/CACD_labs/lab_03/lab_03.sim/sim_1/behav/xsim/xsim.dir/Lab03_FA_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
